// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

[Index("Email", Name = "UQ_Admin_Email", IsUnique = true)]
[Index("User_Name", Name = "UQ_Admins_UserName", IsUnique = true)]
[Index("User_Name", Name = "UQ__Admins__681E8A606691CBBC", IsUnique = true)]
public partial class Admin
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string User_Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Password { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(11)]
    [Unicode(false)]
    public string Phone { get; set; }

    public bool IsEmailConfirmed = false;
}