// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

[Index("Email", Name = "UQ_Clients_Email", IsUnique = true)]
[Index("User_Name", Name = "UQ_Clients_UserName", IsUnique = true)]
[Index("User_Name", Name = "UQ__Clients__681E8A6056D92116", IsUnique = true)]
public partial class Client
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string User_Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Password { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    public double? AvgRating { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(11)]
    [Unicode(false)]
    public string Phone { get; set; }

    public bool IsEmailConfirmed = false;
    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    [InverseProperty("Client")]
    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    [InverseProperty("Client")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();
}