// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

public partial class Complaint
{
    [Key]
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TailorId { get; set; }

    [Required]
    [StringLength(200)]
    public string Subject { get; set; }

    [Required]
    public string Message { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Complaints")]
    public virtual Client Client { get; set; }

    [ForeignKey("TailorId")]
    [InverseProperty("Complaints")]
    public virtual Tailor Tailor { get; set; }
}