// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

public partial class DresslyContext : DbContext
{
    public DresslyContext()
    {
    }

    public DresslyContext(DbContextOptions<DresslyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<Fabric> Fabrics { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<Tailor> Tailors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Admins__3214EC0774F4A7D2");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC079670D4E1");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clients__3214EC07E113022D");

            entity.Property(e => e.AvgRating).HasDefaultValue(0.0);
        });

        modelBuilder.Entity<Complaint>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Complain__3214EC0762E40ECC");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("Pending");

            entity.HasOne(d => d.Client).WithMany(p => p.Complaints).HasConstraintName("FK_Complaints_Clients");

            entity.HasOne(d => d.Tailor).WithMany(p => p.Complaints).HasConstraintName("FK_Complaints_Tailors");
        });

        modelBuilder.Entity<Fabric>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Fabrics__3214EC072EC64168");

            entity.HasOne(d => d.Category).WithMany(p => p.Fabrics).HasConstraintName("FK__Fabrics__Categor__440B1D61");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Favorite__3214EC0715A19B65");

            entity.HasOne(d => d.Client).WithMany(p => p.Favorites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__Clien__4AB81AF0");

            entity.HasOne(d => d.Fabric).WithMany(p => p.Favorites).HasConstraintName("FK__Favorites__Fabri__4CA06362");

            entity.HasOne(d => d.Tailor).WithMany(p => p.Favorites).HasConstraintName("FK__Favorites__Tailo__4BAC3F29");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Feedback__3214EC07D4BC26DC");

            entity.Property(e => e.Date).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Client).WithMany(p => p.Feedbacks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedbacks__Clien__5165187F");

            entity.HasOne(d => d.Tailor).WithMany(p => p.Feedbacks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Feedbacks__Tailo__52593CB8");
        });

        modelBuilder.Entity<Offer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Offers__3214EC07965E33CE");

            entity.HasOne(d => d.Fabric).WithMany(p => p.Offers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Offers__FabricId__47DBAE45");

            entity.HasOne(d => d.Tailor).WithMany(p => p.Offers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Offers__TailorId__46E78A0C");
        });

        modelBuilder.Entity<Tailor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tailors__3214EC0791F355C7");

            entity.Property(e => e.AvgRating).HasDefaultValue(0.0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}