// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

public partial class Favorite
{
    [Key]
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int? TailorId { get; set; }

    public int? FabricId { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Favorites")]
    public virtual Client Client { get; set; }

    [ForeignKey("FabricId")]
    [InverseProperty("Favorites")]
    public virtual Fabric Fabric { get; set; }

    [ForeignKey("TailorId")]
    [InverseProperty("Favorites")]
    public virtual Tailor Tailor { get; set; }
}