// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

public partial class Feedback
{
    [Key]
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TailorId { get; set; }

    public int? Rating { get; set; }

    [StringLength(500)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Feedbacks")]
    public virtual Client Client { get; set; }

    [ForeignKey("TailorId")]
    [InverseProperty("Feedbacks")]
    public virtual Tailor Tailor { get; set; }
}