// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dreslay.Models;

public partial class Offer
{
    [Key]
    public int Id { get; set; }

    public int TailorId { get; set; }

    public int FabricId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(500)]
    public string Note { get; set; }

    [ForeignKey("FabricId")]
    [InverseProperty("Offers")]
    public virtual Fabric Fabric { get; set; }

    [ForeignKey("TailorId")]
    [InverseProperty("Offers")]
    public virtual Tailor Tailor { get; set; }
}